using System;

namespace EulerProject.Problems
{
    public partial class ProblemsContainer
    {
        /// <summary>
        /// Problem 2.
        /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
        /// By starting with 1 and 2, the first 10 terms will be:
        /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        /// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
        /// find the sum of the even-valued terms.
        /// </summary>
        /// <returns>Sum of even-valued terms</returns>
        public int SolveProblem02(int maxFibonacciValue = 4000)
        {
            int sum = 2;

            // As we don't need to store all of Fibonacci numbers:
            // Array containing the last two elements of the sequence.
            int[] lastFibonacciValues = new[] { 1, 2 };

            while (true)
            {
                var newValue = lastFibonacciValues[1] + lastFibonacciValues[0];

                if (newValue > maxFibonacciValue)
                    break;

                lastFibonacciValues[0] = lastFibonacciValues[1];
                lastFibonacciValues[1] = newValue;

                if (newValue % 2 == 0)
                {
                    sum += newValue;
                }
            }

            return sum;
        }
    }
}
